BEGIN TRANSACTION;
CREATE TABLE ingredients (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO ingredients VALUES(1,'Fish');
INSERT INTO ingredients VALUES(2,'Nori');
INSERT INTO ingredients VALUES(3,'Rice');
INSERT INTO ingredients VALUES(4,'Beef');
INSERT INTO ingredients VALUES(5,'Teryaki sauce');
INSERT INTO ingredients VALUES(6,'Tuna');
INSERT INTO ingredients VALUES(7,'Salmon');
CREATE TABLE recipes (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO recipes VALUES(1,'Sushi');
INSERT INTO recipes VALUES(2,'Beef Teryaki');
INSERT INTO recipes VALUES(3,'Sashimi');
CREATE TABLE recipes_ingredients (ingredient_id NUMERIC, recipe_id NUMERIC);
INSERT INTO recipes_ingredients VALUES(1,1);
INSERT INTO recipes_ingredients VALUES(2,1);
INSERT INTO recipes_ingredients VALUES(3,1);
INSERT INTO recipes_ingredients VALUES(4,2);
INSERT INTO recipes_ingredients VALUES(5,2);
INSERT INTO recipes_ingredients VALUES(6,3);
INSERT INTO recipes_ingredients VALUES(7,3);
COMMIT;
